<a href="https://colab.research.google.com/github/Retr0Sys/Clasificaci-n-de-sentimientos-en-publicaciones-CFE-IA/blob/main/Clasificaci%C3%B3n_PLN_de_sentimientos_en_publicaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Importamos librerias y leemos el .csv**

In [72]:
import pandas as pd
df = pd.read_csv('dataset_train.csv')
df.head()

,id,user,text,date,emotion,sentimento
0,126,@_blutsxchtig,"Se refiere a Phel, casi se muere él. Hoy. Y lu...","Jan 5, 2024 · 9:11 PM UTC",overwhelmed,0
1,2510,@jazminmoree,JAJAJJAA cada atrevido cae a ranchar a casa,"Jan 6, 2024 · 1:18 AM UTC",daring,1
2,2452,@MrFibrosis,Ahora fuera de joda y ya que le interesa a tod...,"Jan 6, 2024 · 1:43 AM UTC",optimistic,1
3,934,@potasini,"Que hago con esta necesidad de afecto, me sien...","Jan 6, 2024 · 3:06 AM UTC",isolated,0
4,524,@Exasperante__,Siiiiii estamos adentro jajajajaja por fin lpm,"Jan 5, 2024 · 7:46 PM UTC",irritated,0

## **Verificaciones de nulo**

In [73]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2072 entries, 0 to 2071
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          2072 non-null   int64
 1   user        2072 non-null   object
 2   text        2072 non-null   object
 3   date        2072 non-null   object
 4   emotion     2072 non-null   object
 5   sentimento  2072 non-null   int64
dtypes: int64(2), object(4)
memory usage: 97.3+ KB

id            0
user          0
text          0
date          0
emotion       0
sentimento    0
dtype: int64

## **Verificamos si hay datos vacios**

In [74]:
print("Cantidad de filas antes de eliminar duplicado", df.shape)
df.drop_duplicates(inplace=True)
print("Cantidad de filas después de eliminar duplicado", df.shape)

Cantidad de filas antes de eliminar duplicado (2072, 6)
Cantidad de filas después de eliminar duplicado (2072, 6)

## **Entrenamos el modelo**

In [75]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['sentimento'], test_size=0.10)

In [76]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizador = CountVectorizer()
X_train_vec = vectorizador.fit_transform(X_train)
X_test_vec = vectorizador.transform(X_test)

In [77]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

modelo = LogisticRegression()
modelo.fit(X_train_vec, y_train)

predit = modelo.predict(X_test_vec)

accuracy = accuracy_score(y_test, predit)
print("Porcentaje de acierto:", accuracy * 100)

Porcentaje de acierto: 86.0576923076923

## **Leemos el .csv sin la etiqueta objetivo**

In [78]:
pruebas = pd.read_csv('dataset_test_sin_sentimento.csv')
pruebas.head()

,id,user,text,date,emotion
0,1836,@awjdrm84,"Bravos es el verdadero medidor de Leones, con ...","Jan 6, 2024 · 3:33 AM UTC",confident
1,2502,@alejandracinco,Bien atrevido yop,"Jan 6, 2024 · 3:04 AM UTC",daring
2,1561,@JuliiRojas_m,Es increíble la capacidad de recordar momentos...,"Jan 2, 2024 · 11:20 AM UTC",thankful
3,393,@anac_atencia,"Quiero unos patines, ese siempre ha sido mi re...","Jan 6, 2024 · 3:33 AM UTC",jealous
4,677,@cldyqs,PQ ESTA TAN DISTANTE ME WUIEO4 MATAT,"Jan 6, 2024 · 3:27 AM UTC",distant

## **Generamos el archivo .csv**

In [79]:
X_test_vec = vectorizador.transform(pruebas['text'])

predict = modelo.predict(X_test_vec)

output = pd.DataFrame({'ID': pruebas['id'], 'etiqueta': predict})
output.to_csv('submission.csv', index=False)

print("Archivo creado con éxito")

Archivo creado con éxito